// File generated by Antigravity IDE.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'FirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLjShoGXxW6wmC930HNg8aiO1JzPi6vw',
    appId: '1:602563067692:web:a62b881ad36ce6d3b73689',
    messagingSenderId: '602563067692',
    projectId: 'diacareai-e8700',
    authDomain: 'diacareai-e8700.firebaseapp.com',
    databaseURL: 'https://diacareai-e8700-default-rtdb.firebaseio.com',
    storageBucket: 'diacareai-e8700.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNLjShoGXxW6wmC930HNg8aiO1JzPi6vw',
    appId: '1:602563067692:android:08990ba4beee53dcb73689',
    messagingSenderId: '602563067692',
    projectId: 'diacareai-e8700',
    databaseURL: 'https://diacareai-e8700-default-rtdb.firebaseio.com',
    storageBucket: 'diacareai-e8700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNLjShoGXxW6wmC930HNg8aiO1JzPi6vw',
    appId: '1:602563067692:ios:76d49ca7beee53dcb73689',
    messagingSenderId: '602563067692',
    projectId: 'diacareai-e8700',
    databaseURL: 'https://diacareai-e8700-default-rtdb.firebaseio.com',
    storageBucket: 'diacareai-e8700.firebasestorage.app',
    iosBundleId: 'com.example.projectMobtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNLjShoGXxW6wmC930HNg8aiO1JzPi6vw',
    appId: '1:602563067692:ios:76d49ca7beee53dcb73689',
    messagingSenderId: '602563067692',
    projectId: 'diacareai-e8700',
    databaseURL: 'https://diacareai-e8700-default-rtdb.firebaseio.com',
    storageBucket: 'diacareai-e8700.firebasestorage.app',
    iosBundleId: 'com.example.projectMobtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNLjShoGXxW6wmC930HNg8aiO1JzPi6vw',
    appId: '1:602563067692:windows:ee12a9ca7beee53dcb73689',
    messagingSenderId: '602563067692',
    projectId: 'diacareai-e8700',
    databaseURL: 'https://diacareai-e8700-default-rtdb.firebaseio.com',
    storageBucket: 'diacareai-e8700.firebasestorage.app',
  );
}
